export {default as MDnsIcon} from './MDnsIcon'
export {default as MEmojiEventsIcon} from './MEmojiEventsIcon'
export {default as MGraduationIcon} from './MGraduationIcon'
export {default as MAccessTimeIcon} from './MAccessTimeIcon'
export {default as MNewTabIcon} from './MNewTabIcon'